Vertical tabset
blackbaud/skyux1 pull request #1024
Opened 2017-04-28 12:32 UTC by Blackbaud-BenCook

#899 @Blackbaud-ToddRoberts, @Blackbaud-Robfavre, and @Blackbaud-TimHammond, please let me know if you see any areas that need adjusted for conforming to the spec.

@Blackbaud-PatrickOFriel, I'm not sure if more work is needed around the visual tests. The tests I added pass locally, but I didn't check in new baseline screenshots. I noticed that the screenshots generated in `webdriver-screenshotslocal` don't actually look correct (the way that the component appears in the docs). I'm not sure if some styles are not getting pulled in or what. Let me know if you have any guidance.

2017-04-28 12:49 UTC, blackbaud-sky-savage commented
**Tests failed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: e14e97e4cee05712573fafe9b353f1273458c9a3
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/226794737

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

2017-04-28 13:27 UTC, Blackbaud-TimHammond commented
@Blackbaud-BenCook where can I see what this looks like? Is there a demo somewhere?

2017-04-28 13:30 UTC, Blackbaud-BenCook commented
You'd need to build and serve the docs locally. Here are some screenshots:

2017-04-28 13:32 UTC, Blackbaud-PatrickOFriel commented
I'll start taking a look at this next week

2017-04-28 13:55 UTC, Blackbaud-TimHammond commented
@Blackbaud-BenCook, that looks great except for a couple small alignment issues. In the tabs without groups, there is a small amount of extra left padding on the selected tab label.

For the grouped tabs, the sub tabs should be indented to the right so that the blue left border falls directly under the group name. As with the tabs without groups, the grouped tab labels should also be aligned.

If it's easier, I can swing by your desk to work through these issues.

2017-04-28 15:14 UTC, Blackbaud-ToddRoberts commented
Could you update the tab list invoking button in the mobile version to reflect the design in https://blackbaudinc.box.com/s/eb38jct0ty1librzhaorku3adolhrapt (left chevron, noun-based reference to tab list)? I know the actual implementation of the button will be up to the consuming app but would like to provide the example of how we would expect it to look.

2017-04-28 16:03 UTC, Blackbaud-BenCook commented
@Blackbaud-ToddRoberts, yes, I'll do that. @Blackbaud-TimHammond, I believe I understand what you're saying, but if I encounter anything I have a question about, I'll ping you on Slack.

2017-04-28 17:55 UTC, blackbaud-sky-savage commented
**Tests failed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: d2b3b23698ca2630bdbfaf13d1d0f78834e97c9c
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/226903980

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

2017-05-03 13:36 UTC, Blackbaud-PatrickOFriel commented
One visual thing I noticed is that you can tab to the vertical tab group, but there's no focus indication to let you know where you are at

2017-05-03 13:48 UTC, Blackbaud-BenCook commented
Okay, I'll make that addition in the next day or two.

2017-05-03 14:51 UTC, Blackbaud-PatrickOFriel requested changes

2017-05-03 14:51 UTC, Blackbaud-PatrickOFriel commented on js/sky/src/tabset/tabset.js
> +    BBVerticalTabsetController.$inject = [];
If you're not injecting anything you don't need this line

2017-05-03 14:51 UTC, Blackbaud-PatrickOFriel commented on js/sky/src/tabset/tabset.js
> +    bbVerticalTabsetGroup.$inject = [];
Same as above

2017-05-03 14:51 UTC, Blackbaud-PatrickOFriel commented on webdrivertest/test/tabset/tabset.visual.js
> +    }
Change this to: 
```
function verticalTabsetTest(screenWidth, groups, name) {
        var selector = groups ? '#screenshot-vertical-tabset-groups' : '#screenshot-vertical-tabset-no-groups';
        return browser
            .setupTest('/tabset/fixtures/test.full.html', screenWidth)
            .compareScreenshot({
                screenshotName: 'vertical_tabset_' + name,
                selector: selector,
                checkAccessibility: true
            });
    }
```

2017-05-03 14:51 UTC, Blackbaud-PatrickOFriel commented on webdrivertest/test/tabset/tabset.visual.js
> +    });
Change these tests to: 
```
it('should match the baseline vertical tabset screenshot', function () {
        return verticalTabsetTest(1280, true, 'group');
    });

    it('should match the baseline vertical screenshot on small screens', function () {
        return verticalTabsetTest(480, true, 'group');
    });

    it('should match the baseline vertical tabset without groups screenshot', function () {
        return verticalTabsetTest(1280, false, 'no_group');
    });

    it('should match the baseline vertical tabset without groups screenshot on small screens', function () {
        return verticalTabsetTest(480, false, 'no_group');
    });
```

2017-05-03 14:51 UTC, Blackbaud-PatrickOFriel commented on webdrivertest/test/tabset/fixtures/test.html
> +            <uib-tabset bb-vertical-tabset active="-1">
Change this to active="1" to show the active indication in the visual test

2017-05-03 14:51 UTC, Blackbaud-PatrickOFriel commented on webdrivertest/test/tabset/fixtures/test.html
> +            <uib-tabset bb-vertical-tabset active="-1">
Change this to active="1" to show active indication in visual tests

2017-05-03 14:51 UTC, Blackbaud-PatrickOFriel commented on webdrivertest/test/tabset/fixtures/test.html
> +    <div id="screenshot-tabset-vertical-all">
Add this: `style="height: 500px; width: 1000px; background-color: white"` to simulate correct background color of a normal app and to give bounds to the screenshot.

2017-05-05 11:51 UTC, Blackbaud-BenCook commented on webdrivertest/test/tabset/fixtures/test.html
> +            <uib-tabset bb-vertical-tabset active="-1">
@Blackbaud-PatrickOFriel, I set active="-1" so that the tabs would be visible on mobile screen width. What do you think about doubling the number of visual tests so that we can cover all combinations of grouped tabs/no groups, mobile/desktop, and active tab/no active tab?

2017-05-05 12:44 UTC, Blackbaud-BenCook commented
@Blackbaud-PatrickOFriel, I made your suggested changes, and the generated screenshots look the way I expect now. Thanks! Two questions:

1. Do I need to move the generated screenshots from `webdriver-screenshotslocal` to `webdriver-screenshots` and check them in? Or does that happen as part of the CI?
2. If it is not automatic, do you have any tips for generating the Firefox screenshots? I haven't been able to run visual tests against selenium running locally in Firefox. (Wanted to check with you before I dig into that too much.)

2017-05-05 13:03 UTC, Blackbaud-PatrickOFriel commented
@Blackbaud-BenCook The new screenshots are generated by browserstack as part of the CI

2017-05-05 13:04 UTC, Blackbaud-PatrickOFriel commented on webdrivertest/test/tabset/fixtures/test.html
> +            <uib-tabset bb-vertical-tabset active="-1">
I'd be fine with doubling the number of visual tests to show all combinations

2017-05-05 13:32 UTC, Blackbaud-ToddRoberts commented
@Blackbaud-TimHammond can you take a look at the keyboard focus state and see if it's what you'd expect?

2017-05-05 13:32 UTC, blackbaud-sky-savage commented
**Tests passed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: 09b067599e620600a5c1cbd652004e493a8b2fd1
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/229117837

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

2017-05-05 13:40 UTC, Blackbaud-BenCook commented on js/sky/src/tabset/tabset.js
> +    bbVerticalTabsetGroup.$inject = [];
Oops, this one slipped through the cracks. I'll wait to see if there are any additional changes requested, then check this in with those.

2017-05-05 15:15 UTC, Blackbaud-BenCook commented
@Blackbaud-TimHammond, for your convenience, if you don't need to actually build and run the code, here is what it looks like in Chrome on Windows:

![capture1](https://cloud.githubusercontent.com/assets/25209373/25751643/bfd8c806-3183-11e7-9175-598426bf68f5.JPG)
![capture2](https://cloud.githubusercontent.com/assets/25209373/25751644/bfdf6b7a-3183-11e7-8ca8-2601da97bebc.JPG)

2017-05-05 16:56 UTC, Blackbaud-TimHammond commented
@Blackbaud-BenCook @Blackbaud-ToddRoberts Looks good to me. Thanks!

2017-05-05 17:38 UTC, blackbaud-sky-savage commented
**Tests passed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: c1a37887bb2d4a15312e499a0ae1d6e47f6fd83c
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/229207296

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

2017-05-05 20:34 UTC, blackbaud-sky-savage commented
**Tests passed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: bb6a0143f7e3b307f9378405eca7e6decefa400b
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/229270414

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

2017-05-05 20:50 UTC, blackbaud-sky-savage commented
**Tests failed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 1f261606d2d06c215f42c62c65c485c68109dc45
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/229275770

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

2017-05-05 20:59 UTC, Blackbaud-PatrickOFriel commented
@blackbaud-sky-savage retry

2017-05-05 21:18 UTC, blackbaud-sky-savage commented
**Tests passed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: 1f261606d2d06c215f42c62c65c485c68109dc45
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/229283844

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

2017-05-05 21:42 UTC, Blackbaud-PatrickOFriel approved these changes

2017-05-05 21:42 UTC, merged