Reorder table
blackbaud/skyux1 pull request #1038
Opened 2017-06-13 18:27 UTC by Blackbaud-StacyCarlos

2017-06-13 18:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/blackbaud/skyux?pullRequest=1038) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/blackbaud/skyux?pullRequest=1038) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/blackbaud/skyux?pullRequest=1038) it.</sub>

2017-06-13 18:40 UTC, blackbaud-sky-savage commented
**Tests failed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 40055a6bc13a00ebeb6606af0629f368bf7c5b08
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/242536092

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

2017-06-13 22:41 UTC, blackbaud-sky-savage commented
**Tests passed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: fdd573b554e1bec216cfb09aa4b668fa4fc98708
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/242617843

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

2017-06-20 21:54 UTC, blackbaud-sky-savage commented
**Tests passed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: aa883747ee51bd39c6017da8e45f42d058d6099d
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/245125735

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

2017-06-28 17:41 UTC, Blackbaud-PatrickOFriel commented
Hey @Blackbaud-StacyCarlos, thanks for creating this pull request!

It looks like this work is based around this pattern, correct? 
https://blackbaudinc.app.box.com/s/how1cpox0x83i2pm7choys5pu5xhg1z5

If that's the case, we're going to ask for a few changes before this can become a part of the SKY UX library. 

The main concern is the `isBool` and `templateFn` properties for columns and the `getContextMenuItems` property. The pattern example we have shows the checkbox and context menu as content of a given table cell. However, we shouldn't assume thats the only possible templates that will need to be inside of a cell (and we can't assume that all of the possible content can be solved by placing a single class on the cell with `templateFn`. Instead of solving specifically with properties for checkbox and contextmenu, for a reusable pattern, we should just allow users to have arbitrary content for a given column (sort of like how bb-grid works). This would also remove the need to have all of the hard-coded logic around `isInverted` and such that exists for the `isBool` functionality right now.

If y'all don't have the capacity to take on the effort to make these changes, we understand, but if that's the case, this implementation should be maintained within your individual product instead of in SKY UX. 

Thanks!

2017-06-28 19:16 UTC, Blackbaud-StacyCarlos commented
Hey @Blackbaud-PatrickOFriel,

I've never seen this design document before, but it seems to pretty accurately describe what I was trying to implement within this directive. When I was originally implementing this, I was focused solely on FE NXT requirements and thought it may be useful as a SKY directive.

Additionally, I have spent a lot more time working with AngularJS now than previously. I will look into adding the `controller` and `template_url` options to the directive, similar to that of bb-grid, and update the pull request as soon as I can.

2017-06-28 19:17 UTC, Blackbaud-PatrickOFriel commented
Thanks, we really appreciate it @Blackbaud-StacyCarlos !

2017-06-30 02:09 UTC, Blackbaud-StacyCarlos commented
Hello again @Blackbaud-PatrickOFriel,

I have implemented the desired functionality into the directive. I have elected to keep the `getContextMenuItems` option as this seems to align more accurately with bbGrid unless you guys require otherwise.

Do you have any areas for improvement?

2017-06-30 02:21 UTC, blackbaud-sky-savage commented
**Tests passed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: ca8cee437c813005fc82d42366dcf0fbab98f4e7
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/248618085

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

2017-06-30 02:37 UTC, blackbaud-sky-savage commented
**Tests passed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: 7adcd3329dddbe6991bbacfd9f8eee7a220d3c00
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/248619038

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

2017-06-30 12:58 UTC, blackbaud-sky-savage commented
**Tests passed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: 1767b00f5f4ac465ad91cbfebf128c2a9826a664
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/248764853

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

2017-06-30 13:05 UTC, Blackbaud-PatrickOFriel commented
Thanks for getting back so quickly, I'll try to do a deep dive review next week

2017-07-07 19:04 UTC, Blackbaud-PatrickOFriel commented on js/sky/src/reordertable/docs/demo.md
> +            - `jsonMap` &mdash; Specifies the name of the property within the `data` property that maps to the data in the column. This property is not needed only if using the `templateFn` property.
Update because the `templateFn` property does not exist anymore.

2017-07-07 19:04 UTC, Blackbaud-PatrickOFriel commented on js/sky/src/reordertable/docs/demo.md
> +            - `template_url` &mdash; *(Optional.)* Specifies the URL for a column template to use when displaying formatted or complex data in a cell. To access the properties of the cell data
Looks like a sentence doesnt end here

2017-07-07 19:09 UTC, Blackbaud-PatrickOFriel commented on js/sky/src/reordertable/docs/demo.js
> +                    '<div class="bb-test-info">Info: {{data.info}}</div>' +
Looks like the info and title aren't actually appearing in the demo, are you seeing the same thing?

2017-07-07 19:17 UTC, Blackbaud-PatrickOFriel commented on js/sky/src/reordertable/reordertable.component.js
> +        vm.isFixed = function (index) {
Just as a matter of style (and to help with debugging) can you make this a function like above? e.g. have a function isFixed() { etc. } and then set vm.isFixed = isFixed;

2017-07-07 19:17 UTC, Blackbaud-PatrickOFriel commented on js/sky/src/reordertable/reordertable.component.js
> +        vm.setFixed = function (index) {
Same as above

2017-07-07 19:17 UTC, Blackbaud-PatrickOFriel commented on js/sky/src/reordertable/reordertable.component.js
> +        vm.pushToTop = function (item) {
Same as above

2017-07-07 19:17 UTC, Blackbaud-PatrickOFriel commented on js/sky/src/reordertable/reordertable.component.js
> +        vm.cellLink = function (row, index, column) {
Same as above

2017-07-07 19:19 UTC, Blackbaud-StacyCarlos commented on js/sky/src/reordertable/docs/demo.md
> +            - `jsonMap` &mdash; Specifies the name of the property within the `data` property that maps to the data in the column. This property is not needed only if using the `templateFn` property.
I have replaced `templateFn` with `template_url`.

2017-07-07 19:20 UTC, Blackbaud-StacyCarlos commented on js/sky/src/reordertable/docs/demo.md
> +            - `template_url` &mdash; *(Optional.)* Specifies the URL for a column template to use when displaying formatted or complex data in a cell. To access the properties of the cell data
I have completed the sentence to match bbGrid.

2017-07-07 19:23 UTC, Blackbaud-StacyCarlos commented on js/sky/src/reordertable/docs/demo.js
> +                    '<div class="bb-test-info">Info: {{data.info}}</div>' +
Forgot to add the `jsonMap` column property. It has now been added.

2017-07-07 19:27 UTC, Blackbaud-PatrickOFriel commented on js/sky/src/reordertable/reordertable.component.js
> +                    /*angular.forEach(vm.options.data, function (item) {
let's remove this comment

2017-07-07 19:30 UTC, Blackbaud-StacyCarlos commented on js/sky/src/reordertable/reordertable.component.js
> +        vm.isFixed = function (index) {
Has been changed as stated.

2017-07-07 19:30 UTC, Blackbaud-StacyCarlos commented on js/sky/src/reordertable/reordertable.component.js
> +        vm.setFixed = function (index) {
Has been changed as stated.

2017-07-07 19:30 UTC, Blackbaud-StacyCarlos commented on js/sky/src/reordertable/reordertable.component.js
> +        vm.pushToTop = function (item) {
Has been changed as stated.

2017-07-07 19:30 UTC, Blackbaud-StacyCarlos commented on js/sky/src/reordertable/reordertable.component.js
> +        vm.cellLink = function (row, index, column) {
Has been changed as stated.

2017-07-07 19:31 UTC, Blackbaud-StacyCarlos commented on js/sky/src/reordertable/reordertable.component.js
> +                    /*angular.forEach(vm.options.data, function (item) {
Removed

2017-07-07 19:33 UTC, Blackbaud-PatrickOFriel commented on js/sky/templates/reordertable/reordertable.component.html
> +<div class="bb-reorder-table" id="bb-reorder-table-{{$ctrl.tableName}}">
tableName is never set

2017-07-07 19:36 UTC, Blackbaud-PatrickOFriel commented on js/sky/templates/reordertable/reordertable.component.html
> +                <div ng-if="column.show" ng-repeat="column in $ctrl.options.columns" class="bb-reorder-table-col" ng-style="{ 'width': column.width }" id="{{'bb-reorder-table-cell-' + rowIndex + '-'
If you use an id, it's very important to ensure that the id is unique. In the past we've set $scope.$id to a variable that's usable within a template and done something like 'bb-reorder-table-' + $ctrl.tableId + '-cell-' + rowIndex + '-' + colName. This way if you have two reorder tables on the same page with the same column name, you can still have unique ids. I would also do this for the bb-reorder-table id you've used above if it really needs to be an id.

2017-07-07 19:37 UTC, Blackbaud-StacyCarlos commented on js/sky/templates/reordertable/reordertable.component.html
> +<div class="bb-reorder-table" id="bb-reorder-table-{{$ctrl.tableName}}">
This I had a question about.

Would the option to give the table a unique id be useful? If not, this can be removed.

2017-07-07 19:37 UTC, Blackbaud-PatrickOFriel commented on js/sky/templates/reordertable/reordertable.component.html
> +<div class="bb-reorder-table" id="bb-reorder-table-{{$ctrl.tableName}}">
I'd remove it unless there's a really pressing reason to have an id

2017-07-07 19:38 UTC, Blackbaud-StacyCarlos commented on js/sky/templates/reordertable/reordertable.component.html
> +                <div ng-if="column.show" ng-repeat="column in $ctrl.options.columns" class="bb-reorder-table-col" ng-style="{ 'width': column.width }" id="{{'bb-reorder-table-cell-' + rowIndex + '-'
Okay, this answered my precious question.

2017-07-07 19:55 UTC, Blackbaud-PatrickOFriel commented on js/sky/src/reordertable/reordertable.component.js
> +            itemScope = $scope.$new(true);
We need to destroy the existing itemScopes whenever the rows are reloaded, otherwise they'll stick around in memory. Check out the `destroyCellScopes` function in grids.js

2017-07-07 19:58 UTC, Blackbaud-PatrickOFriel commented on js/sky/templates/reordertable/reordertable.component.html
> +                    <div ng-if="$ctrl.sorting && !$ctrl.isFixed($index)" class="bb-reorder-table-cell">
What does this part of the template do here?

2017-07-07 19:59 UTC, Blackbaud-PatrickOFriel commented on js/sky/src/reordertable/reordertable.component.js
> +                        containerEl.sortable("refreshPositions");
Lets use single quotes to maintain consistency

2017-07-07 20:02 UTC, Blackbaud-StacyCarlos commented on js/sky/templates/reordertable/reordertable.component.html
> +                    <div ng-if="$ctrl.sorting && !$ctrl.isFixed($index)" class="bb-reorder-table-cell">
This is a place holder for the numbers that appear when sorting. This is exactly the same implementation as the bbReorder directive.

2017-07-07 20:03 UTC, Blackbaud-PatrickOFriel commented on js/sky/templates/reordertable/reordertable.component.html
> +                    <div ng-if="$ctrl.sorting && !$ctrl.isFixed($index)" class="bb-reorder-table-cell">
Ah gotcha, I see now

2017-07-07 20:10 UTC, Blackbaud-PatrickOFriel commented
In the demo, can you add something like what's in the reorder demo, which displays the two-way binding result: e.g.: 
```
<div style="margin-top: 10px;">
    <h4>Current order:</h4>

    <ul ng-repeat="item in reorderCtrl.itemsToSort">
      <li>{{item.title}}</li>
    </ul>
  </div>
```

2017-07-07 20:13 UTC, Blackbaud-PatrickOFriel commented on scss/_reordertable.scss
> +    //overflow-y: visible !important;
Any reason these comments in this css exists?

2017-07-07 20:14 UTC, Blackbaud-StacyCarlos commented on scss/_reordertable.scss
> +    //overflow-y: visible !important;
Nope, I can remove those.

2017-07-07 20:14 UTC, Blackbaud-PatrickOFriel commented on scss/_reordertable.scss
> +    overflow-x: visible !important;
We like to avoid !important if at all possible. It's kind of the nuclear option for css rules. I'd rather you just use a more specific rule than whatever is overriding the overflow-x

2017-07-07 20:18 UTC, Blackbaud-PatrickOFriel commented on scss/_reordertable.scss
> +                border: 1px solid #CCC;
Use the mixin `@include bb-border(dark, top, bottom, left, right)`. (You'll need to include `@import "mixins";` at the top of this file as well.

2017-07-07 20:19 UTC, Blackbaud-PatrickOFriel commented on scss/_reordertable.scss
> +                color: #707374;
Use the variable `$sky-text-deemphasized-color` here.

2017-07-07 20:20 UTC, Blackbaud-PatrickOFriel commented on scss/_reordertable.scss
> +            border-top: dotted 1px $gray-lighter;
Use the mixin: @include bb-border(row, top);

2017-07-07 20:20 UTC, Blackbaud-PatrickOFriel commented on scss/_reordertable.scss
> +    /*>:not(.bb-reorder-table-row-placeholder):not(.bb-reorder-list-sorting-item):nth-of-type(even) {
Let's remove this comment if it's unnecessary

2017-07-07 20:22 UTC, Blackbaud-PatrickOFriel commented on scss/_reordertable.scss
> +              color: #CCC;
Let's use $gray-lighter here

2017-07-07 20:23 UTC, Blackbaud-PatrickOFriel commented on scss/_reordertable.scss
> +  background-color: #f3f3f4;
Let's use $body-bg here

2017-07-07 20:23 UTC, Blackbaud-PatrickOFriel commented on scss/_reordertable.scss
> +   transition: none !important;
Let's not use !important unless absolutely necessary

2017-07-07 20:28 UTC, Blackbaud-PatrickOFriel commented
The last thing I can see that we'll need to fix before getting this in is how the component responds when the window size changes. For example, when I shrink the demo to less than 600px, there are some visual artifacts that we wouldn't want.

2017-07-08 00:55 UTC, blackbaud-sky-savage commented
**Tests passed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: cfa64861ba61b6a775344823eb3475963d61c916
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/251362130

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

2017-07-08 15:26 UTC, blackbaud-sky-savage commented
**Tests failed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: bf2ad798f66081543584eb50df49fa6f44362246
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/251501963

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

2017-07-08 17:43 UTC, blackbaud-sky-savage commented
**Tests passed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: 6f03548d2e79be7633440f9f13ab42e7d5c0f692
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/251526083

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

2017-07-08 23:49 UTC, blackbaud-johnly reviewed
I reviewed the docs. They mostly look good, but I saw a handful of places where things should be tweaked. I provided feedback in comments. Please just let me know if anything is unclear.

2017-07-08 23:49 UTC, blackbaud-johnly commented on js/sky/src/reordertable/docs/demo.md
> +summary: The reorder component provides an interface to display a table where users can drag-and-drop rows into their preferred order. With additional design functionality
"reorder component" should be "reorder table."

Also, the second sentence is a fragment. I don't think we need a second sentence here given that the summary should be short, but if we want a second sentence, we need to flesh out the current sentences into a complete sentence and explain what we mean by "additional design functionality."

2017-07-08 23:49 UTC, blackbaud-johnly commented on js/sky/src/reordertable/docs/demo.md
> +The reorder table component creates a table where users can drag-and-drop rows into their preferred order. It should be used for display slightly more complex information
I'd change "should be used for display" to "can handle"

2017-07-08 23:49 UTC, blackbaud-johnly commented on js/sky/src/reordertable/docs/demo.md
> +            - `jsonMap` &mdash; Specifies the name of the property within the `data` property that maps to the data in the column. This property is not required when `template_url`, but is required f
Why is "M" capitalized in "jsonMap"? In the same property on the grids directive, the "M" is lowercase.

Should we have "is used" after "`template_url`"?

2017-07-08 23:49 UTC, blackbaud-johnly commented on js/sky/src/reordertable/docs/demo.md
> +            - `show` &mdash; *(Optional.)* Specifies whether or not the given column is visible. *(Default: `true`)*
I'd change "Specifies" to "Indicates." (We generally use "indicates" instead of "specifies" for Booleans.)

And delete "or not."

2017-07-08 23:49 UTC, blackbaud-johnly commented on js/sky/src/reordertable/docs/demo.md
> +            - `width` &mdash; *(Optional.)* Specifies the desired width attribute of the column elements. The width of the columns will not be respected if they are smaller than the table together. *
Why do we have "attribute" in the first sentence? I assume this specifies the width, not an attribute related to width. Is that right? If so, delete "attribute." If not, I think we need to explain what attribute we are referring to here.

Also, I assume this property sets the width for a particular column. If so, delete "elements" at the end of the first sentence.

Next, does the second sentence mean that if the combined widths of all the columns are smaller than the table, then the specified widths are not respected? If so, I'd change this second sentence to "The column width is not respected if the combined column widths are smaller than the table." But if not, what do we mean here?

And finally, delete the garbage text after the closing astrisk for the default.

2017-07-08 23:49 UTC, blackbaud-johnly commented on js/sky/src/reordertable/docs/demo.md
> +        - `fixed` &mdash; *(Optional.)* Specifies a number of rows at the top of the table which can no be reordered. *(Default: `0`)*
Change "which can no be reordered" to "that users cannot reorder." (This switches to active voice and fixes the "no" typo.)

2017-07-08 23:49 UTC, blackbaud-johnly commented on js/sky/src/reordertable/docs/demo.md
> +        - `getContextMenuItems` &mdash; (Optional.) Specifies a function that allows table rows to create a context menu based on the function's return value. The function returns an array of objects
"(Optional.)" should have asterisks around it.

2017-07-08 23:49 UTC, blackbaud-johnly commented on js/sky/src/reordertable/docs/demo.md
> +        - `index` &mdash; An integer property of the objects in `data` that is used to sort and identify each item. When sortable, this property will altered to match the index of the element.
Should this entry start with "Specifies"?

I'd change "is used to sort and identify" to "sorts and identifies" to use active voice.

What are we referring to in "When sortable"? The table? The index property? I'm not sure. Can we be explicit and say "When XXX is sortable..." with XXX being whatever it is that is sortable?

Finally, I think we need to change "will" to "is." If that's not right, something else needs to change here because "will altered" doesn't make sense.

2017-07-08 23:49 UTC, blackbaud-johnly commented on js/sky/src/reordertable/docs/demo.md
> +        - `oneIndexed` &mdash; *(Optional.)* Specifies if the the property used for `index` is one-indexed. *(Default: `false`)*
Change "Specifies" to "Indicates" and "if" to "whether" for consistency.

Can we delete "used"? Can't tell if it's adding anything here, but I don't think so.

Do we need to explain what we mean by "one-indexed"? I don't know what this means, but maybe this is implicit for the intended audience.

2017-07-08 23:49 UTC, blackbaud-johnly commented on js/sky/src/reordertable/docs/demo.md
> +    - `bb-reorder-table-unsortable` &mdash; Specifies whether or not the list is currently unsortable. *(Default: `false`)*
I'd change "Specifies" to "Indicates" for consistency and delete "or not."

Can we also delete "currently"? I don't think the meaning changes without it.

2017-07-09 14:56 UTC, Blackbaud-StacyCarlos commented on js/sky/src/reordertable/docs/demo.md
> +summary: The reorder component provides an interface to display a table where users can drag-and-drop rows into their preferred order. With additional design functionality
No, the second sentence isn't needed. I was using that fragment as a place holder if more functionality was added later.

2017-07-09 15:15 UTC, Blackbaud-StacyCarlos commented on js/sky/src/reordertable/docs/demo.md
> +        - `oneIndexed` &mdash; *(Optional.)* Specifies if the the property used for `index` is one-indexed. *(Default: `false`)*
One-indexed means counting begins at 1, i.e. 1, 2, 3...

The other method is zero indexing which begins counting at 0. Yes, this is implicit for the audience.

2017-07-09 16:12 UTC, blackbaud-sky-savage commented
**Tests passed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: abce18260987586c01362f556939da8e4d0064b4
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/251738905

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

2017-07-10 01:39 UTC, blackbaud-sky-savage commented
**Tests passed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: 9c4bb16423913af54b27ddb98069efeeffe8d5a1
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/251841586

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

2017-07-10 21:03 UTC, Blackbaud-PatrickOFriel commented on scss/_reordertable.scss
> +                .top-disabled {
Where is this class used? and if it is used somewhere we should add the `bb-reorder-table` prefix

2017-07-10 21:14 UTC, Blackbaud-StacyCarlos commented on scss/_reordertable.scss
> +                .top-disabled {
It is no longer used and can be removed.

2017-07-10 21:42 UTC, blackbaud-sky-savage commented
**Tests passed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: f009bffee16bf3a1c17afa718bf06a1428bb3a8b
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/252175884

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

2017-07-12 19:38 UTC, Blackbaud-PatrickOFriel commented
Hey @Blackbaud-StacyCarlos the only thing I need to get done before merging this is to get the behavior when the window is small working properly. Maybe make a horizontal scrollbar appear by adding a max-width and overflow-x: auto?

2017-07-12 22:50 UTC, blackbaud-sky-savage commented
**Tests passed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: 7b0bbe8cf09ca8f6e06279aac7660c9a34bd0a32
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/252999717

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

2017-07-25 13:01 UTC, Blackbaud-StacyCarlos commented
Hey @Blackbaud-PatrickOFriel,

Do you have anything else I need to do on this or is this complete on my end?

2017-07-25 13:25 UTC, Blackbaud-PatrickOFriel commented
Hey @Blackbaud-StacyCarlos, we've been a bit sidetracked by our color and font change releases the last couple weeks. I'll take a look at both of your pull requests today!

2017-07-25 13:29 UTC, Blackbaud-StacyCarlos commented
@Blackbaud-PatrickOFriel 
No worries. Just wanted to make sure your weren't waiting on me.

2017-07-25 13:40 UTC, Blackbaud-PatrickOFriel requested changes

2017-07-25 13:40 UTC, Blackbaud-PatrickOFriel commented on js/sky/src/reordertable/docs/demo.html
> +  <div style="width: 600px">
To make your changes around mobile responsiveness work properly in the demo, change this to a max-width

2017-07-25 13:40 UTC, Blackbaud-PatrickOFriel commented on js/sky/src/reordertable/docs/demo.html
> +  <div style="width: 500px;">
To make your changes around mobile responsiveness work properly in the demo, change this to a max-width

2017-07-25 13:40 UTC, Blackbaud-PatrickOFriel commented on scss/_reordertable.scss
> +        min-width: 600px;
Is there any particular reason that this is 600px?

2017-07-25 13:42 UTC, Blackbaud-StacyCarlos commented on scss/_reordertable.scss
> +        min-width: 600px;
No particular reason. It can be set to whatever value.

2017-07-25 13:46 UTC, blackbaud-sky-savage commented
**Tests failed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 038e40f02a0dd244591ebbe2f747d1ce7828a63d
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/257304936

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

2017-07-25 13:47 UTC, Blackbaud-PatrickOFriel commented on scss/_reordertable.scss
> +        min-width: 600px;
@Blackbaud-ToddRoberts, thoughts on setting this value?

2017-07-25 15:19 UTC, Blackbaud-ToddRoberts commented on scss/_reordertable.scss
> +        min-width: 600px;
don't think we need a min width here, we generally don't set one on other components of this nature

2017-07-25 17:38 UTC, blackbaud-sky-savage commented
**Tests passed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: a8cfe2ceee9c39af98b5fc1a68e0db3b5d460e05
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/257398959

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

2017-07-25 17:56 UTC, blackbaud-sky-savage commented
**Tests passed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: f6153849d78b2a0dbb06296ccae9fc567d200178
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/257399076

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

2017-07-25 18:33 UTC, Blackbaud-PatrickOFriel commented
@Blackbaud-ToddRoberts this looks good to me, can you do one more look-over to see if I'm missing anything design-wise?

2017-07-26 18:57 UTC, Blackbaud-PatrickOFriel approved these changes

2017-07-26 18:57 UTC, merged