Listbuilder repeater view
blackbaud/skyux1 pull request #882
Opened 2016-10-18 15:48 UTC by Blackbaud-PatrickOFriel

2016-10-19 17:32 UTC, Blackbaud-PaulCrowder requested changes

2016-10-19 17:32 UTC, Blackbaud-PaulCrowder commented on js/sky/src/listbuilder/docs/demo.html
> +          <bb-listbuilder-repeater-item ng-repeat="item in listCtrl.data">
This could probably be accomplished with an attribute directive rather than a parent directive of `bb-repeater`.  This would preserve the documented hierarchy of `bb-repeater`.

2016-10-20 13:50 UTC, Blackbaud-PatrickOFriel commented
@Blackbaud-PaulCrowder updated to use attribute directives for repeater items instead of components

2016-10-21 14:17 UTC, Blackbaud-PaulCrowder approved these changes

2016-10-21 14:17 UTC, merged