Split view
blackbaud/skyux1 pull request #973
Opened 2017-01-12 17:33 UTC by Rahulitsmca

This is the initial version of split view pattern. 

I need to confirm regarding the generic implementation of dirty check validation on any under the sky component.

**checkDirtyForm** method in **demo.js**

use-case is -
One item is selected by clicking anywhere on the row and the fields to edit that selected item show in the workspace.  The actions for that item (process, record, save, etc) are at the bottom of the workspace. And these actions apply to the selected item in the list, not all items at once.  Therefore, if the user changes a field in the workspace and then navigates between items or to another area in primary navigation – they'll be given a [confirmation dialog ](https://blackbaudinc.box.com/s/8gmc9ihomov8l30etpm5rykzc3viixz7) to save or not.

Please let me know in case you need more information or if I missed anything to mention.

Component snapshots:
![component snapshot ](https://cloud.githubusercontent.com/assets/665277/21900711/d6cbaffe-d91a-11e6-8c89-622b74a9f34d.png)

Confirm dialog:
![confirm dialog](https://cloud.githubusercontent.com/assets/665277/21900771/0e90ad36-d91b-11e6-9654-fcacf80e26ce.png)

2017-01-12 17:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/blackbaud/skyux?pullRequest=973) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/blackbaud/skyux?pullRequest=973) before we can accept your contribution.<br/>

2017-01-12 19:50 UTC, Blackbaud-ToddRoberts commented
From the screenshots, styling does not appear to match the spec in: 
https://github.com/blackbaud/skyux/issues/900

2017-01-12 19:51 UTC, Blackbaud-PatrickOFriel commented
Hey @Blackbaud-ToddRoberts, I think this supposed to be a work in progress pull request specifically to get feedback on how to make the form checking generic. Is that correct @Rahulitsmca ?

2017-01-12 19:55 UTC, Blackbaud-ToddRoberts commented
Ok gotcha

2017-01-13 07:36 UTC, Rahulitsmca commented
Thanks @Blackbaud-PatrickOFriel and Yes, you are absolutely correct.
Component is in the intermediate state and I need feedback on the generic implementation of this dirty check form under sky component.

2017-01-26 16:32 UTC, Blackbaud-PatrickOFriel commented
Glancing at this, I see a couple ways we can make this reusable. 

First, create an angular service has a function that wraps up the confirmFormChangePopup modal functionality and opens it. It can have default body text that is something like: "Do you want to save changes to this form? Your changes will be lost if you do not save them.", and that body text can be overridden by passing arguments to the service.

Second, create another angular service that has a function that accepts a form object, a callback that will be called when saving the form, and a callback that will be called when not saving the form. This function will pretty much do the checkDirtyForm function work, (calling the previous service function above to launch the modal).

That's what I've got, what do you think @Blackbaud-BobbyEarl or @Blackbaud-PaulCrowder ?

2017-01-31 14:02 UTC, Rahulitsmca commented
Hey Patrick,

Thanks for looking into the pull request. I got your second point completely that states there should be a service which will expose the method like **checkDirtyForm**. But some confusion in your first point you mentioned to have method like **confirmFormChangePopup** to change the text of confirm modal. 
Consumer can update body in the html during consumption.
Or do you think to remove modal controller ?

2017-01-31 14:24 UTC, Blackbaud-PatrickOFriel commented
@Rahulitsmca Basically I mean allowing some way to make the text in the confirm modal configurable, so that it fits other situations where you have to have the popup

2017-02-08 14:13 UTC, Rahulitsmca commented
Hey Patrick,

I have done the discussed changes in the last two changesets. 

Created a service which exposes  **checkDirtyForm** method and **invokeMethodWithParameters**   . 
I have to expose second method to call after completing the save/donotSave operation.

I have exposed these methods under the **init** method which is responsible to set the options for splitpanel and avoided passing of form object, save, doNotSave in each call to checkDirtyForm.

Is this approach looks good for consumption or needs any improvement?

I'm happy to hear any suggestions 👍   



**Changeset links:**
- https://github.com/blackbaud/skyux/pull/973/commits/0bb7b619dada9d2488533aaa1761224ddafca3b3
- https://github.com/blackbaud/skyux/pull/973/commits/b6af8172f363ac0669353bff2441d0ae26f67188

2017-02-08 14:43 UTC, Blackbaud-PatrickOFriel commented
The general approach looks fine, I'll comment inline on the specific issues I'd like you to take a look at.

2017-02-08 14:44 UTC, Blackbaud-PatrickOFriel commented on js/sky/src/splitpanel/splitpanel.factory.js
> +                            templateUrl: 'demo/splitpanel/confirmpopup.html'
You have the demo modal controller and template hardcoded in here which you will have to change

2017-02-08 14:48 UTC, Blackbaud-PatrickOFriel commented on js/sky/src/splitpanel/splitpanel.factory.js
> +                function invokeMethodWithParameters(func, param) {
I'm not convinced you need to expose this functionality since it seems to be just a generic helper that you would use within the factory

2017-02-08 17:59 UTC, Rahulitsmca commented on js/sky/src/splitpanel/splitpanel.factory.js
> +                function invokeMethodWithParameters(func, param) {
If I do not expose it then I have to invoke passed method in **save** method after the save operation like same or there is any other smart way to invoke this method


`        function save(func, param) {

            alert("data saved");
            //TODO : will save here

            //call it in then block of save 
            if (param === undefined) {
                func();
            } else {
                func(param);
            }
        }
`

2017-02-08 18:00 UTC, Rahulitsmca commented on js/sky/src/splitpanel/splitpanel.factory.js
> +                            templateUrl: 'demo/splitpanel/confirmpopup.html'
Do you mean to pass this two in options?

2017-02-08 18:01 UTC, Blackbaud-PatrickOFriel commented on js/sky/src/splitpanel/splitpanel.factory.js
> +                            templateUrl: 'demo/splitpanel/confirmpopup.html'
I don't particularly care how you do it, but for this ever to be used outside of the demo, then a demo controller and demo template cannot be hardcoded in here.

2017-02-08 18:11 UTC, Blackbaud-PatrickOFriel commented on js/sky/src/splitpanel/splitpanel.factory.js
> +                function invokeMethodWithParameters(func, param) {
I guess I'm kind of confused because in your factory, you call the save callback or not savecallback, and then you also call the `invokeMethodwithParameters`. But the save callback in your demo also calls `invokeMethodWithParameters` within the callback itself. What exactly is the step by step thing that is supposed happening there, what is the example of the 'method' that needs to be invoked, and why would `invokeMethodWithParameters` need to be called twice?

2017-02-08 18:18 UTC, Blackbaud-PatrickOFriel commented on js/sky/src/splitpanel/splitpanel.factory.js
> +                function invokeMethodWithParameters(func, param) {
To me, anything like the invokeMethodWithParameters should just always be within the callers save function itself, and then the factory wouldn't have to worry about it.

2017-02-09 07:35 UTC, Rahulitsmca commented on js/sky/src/splitpanel/splitpanel.factory.js
> +                function invokeMethodWithParameters(func, param) {
Sorry, it's my mistake that was making confusion. I removed **invokeMethodWithParameters** method from factory.
As per my approach **invokeMethodWithParameters** should call only after the success of save operation. 
That is the reason that i have to expose it. Other wise cosumer need to call passed method with parameter like i am doing in factory.

2017-02-09 08:06 UTC, Rahulitsmca commented on js/sky/src/splitpanel/splitpanel.factory.js
> +                function invokeMethodWithParameters(func, param) {
Points I think of during implementations:

- Consumer should invoke all actions by checkDirtyForm method for which he wants dirty check to be run.
-  Action with parameter passed to **checkDirtyForm** method in service
-  If form is dirty then we open popup to ask whether user wants to save/not save.
-  As per selection save/not save operation will perform, then we call the perform action in the resolve block.
-  It's up to the consumer that he want to invoke action on failure of save operation or not by calling **invokeMethodWithParameters** method.

2017-02-15 13:44 UTC, Blackbaud-PatrickOFriel commented on js/sky/src/splitpanel/splitpanel.factory.js
> +                function invokeMethodWithParameters(func, param) {
Ah I see, so your invokeMethodWithParameters basically allows you to pass a callback and a parameter which will be called at various times. @Blackbaud-PaulCrowder we would probably want checkdirtyform to do something like return a promise here instead? That's what we have done in other places

2017-02-15 14:08 UTC, Blackbaud-PatrickOFriel commented on js/sky/src/splitpanel/splitpanel.factory.js
> +    function bbSplitpanelNavigator(bbModal) {
Also this shouldn't really be a bbSplitpanelNavigator since its a pretty generic dirty form checker, it could be used outside of the concept of the split panel.

2017-02-21 13:40 UTC, Rahulitsmca commented on js/sky/src/splitpanel/splitpanel.factory.js
> +    function bbSplitpanelNavigator(bbModal) {
I have named the bbsplitpanelNavigrator factory to **bbCheckDirtyForm** also removed **ListbuilderModalController** from demo.js.

2017-02-21 13:47 UTC, Rahulitsmca commented on js/sky/src/splitpanel/splitpanel.factory.js
> +                function invokeMethodWithParameters(func, param) {
okay. looks cool :)
can you please name any component where we have implemented similar scenario.

2017-07-12 20:14 UTC, Blackbaud-PatrickOFriel commented on js/sky/src/splitpanel/docs/demo.html
> +                            <div class="bb-custom-content-item" bb-splitpanel-list-item ng-repeat="item in listCtrl.data" bb-listbuilder-content-get-panel-data="listCtrl.splitpanelNavigator.checkDirt
bb-listbuilder-content-get-panel-data should have name specific to split panel not listbuilder.

2017-07-12 20:15 UTC, Blackbaud-PatrickOFriel commented on js/sky/src/splitpanel/docs/demo.md
> +`bbCheckDirtyForm.invokeMethodWithParameters` &mdash; Invoke the passed method with parameter.
Can we remove this from the documentation? It isn't used in the demo

2017-07-12 20:17 UTC, Blackbaud-PatrickOFriel commented on js/sky/src/splitpanel/docs/demo.js
> +                occupation: 'Amazon market palce amz.com',
Change occupation property to make more sense with your example (maybe vendor or store? also change the sort item accordingly)

2017-07-12 20:17 UTC, Blackbaud-PatrickOFriel commented on js/sky/src/splitpanel/docs/demo.js
> +                joinDate: new Date('09/14/2016'),
Change joinDate property to make more sense with your example (transaction date or something, change sort and filter options accordingly)

2017-07-12 20:19 UTC, Blackbaud-PatrickOFriel commented on js/sky/src/splitpanel/docs/demo.js
> +                occupation: 'Wallmart',
Walmart

2017-07-12 20:20 UTC, Blackbaud-PatrickOFriel commented on js/sky/src/splitpanel/docs/demo.js
> +            //TODO: loadData with filter of unrecorded transcation
Can this comment go away?

2017-07-12 20:21 UTC, Blackbaud-PatrickOFriel commented on js/sky/src/splitpanel/docs/demo.js
> +            var code = event.keyCode;
Can we take care of this in bb-splitpanel-list-item since everyone using this will need this behavior?

2017-07-12 20:25 UTC, Blackbaud-PatrickOFriel commented on js/sky/src/splitpanel/docs/demo.js
> +            var code = event.keyCode;
Like a callback that's something like bb-splitpanel-list-item-navigate. That attribute can take a callback with a parameter which indicates whether the item should navigate up or down.

2017-07-12 20:31 UTC, Blackbaud-PatrickOFriel requested changes

2017-07-12 20:31 UTC, Blackbaud-PatrickOFriel commented on js/sky/src/splitpanel/docs/demo.md
> +			- `bb-splitpanel-list ` &mdash; Placeholder for list.
bb-split-panel-list-item is not documented

2017-07-12 20:31 UTC, Blackbaud-PatrickOFriel commented on js/sky/src/splitpanel/docs/demo.md
> +			- `bb-splitpanel-list ` &mdash; Placeholder for list.
bb-splitpanel-item-is-active is not documented

2017-07-12 20:36 UTC, Blackbaud-PatrickOFriel commented on js/sky/src/splitpanel/splitpanel.list.filter.component.js
> +///* global angular */
Let's get rid of these comments if we're not using them

2017-07-12 20:38 UTC, Blackbaud-PatrickOFriel commented on js/sky/src/splitpanel/splitpanel.list.item.directive.js
> +                    bbListbuilderContentGetPanelData: '&?'
I mentioned this above, but use Splitpanel instead of Listbuilder here

2017-07-12 20:40 UTC, Blackbaud-PatrickOFriel commented on js/sky/templates/splitpanel/splitpanel.list.panel.directive.html
> +<div class="bb-custom-content" id="splitpanel_list" style="max-width:{{maxWidthInPercentage}}%; min-width:{{minWidthInPercentage  }}%">
This shouldn't be bb-custom-content, it should be prefixed with something splitpanel specific.

2017-07-12 20:40 UTC, Blackbaud-PatrickOFriel commented on js/sky/templates/splitpanel/splitpanel.list.item.component.html
> +<div class="bb-custom-content-selectable-item" ng-click="selectItem()" ng-class="{'selectedItem': bbSplitpanelItemIsActive}" id="item{{$parent.$index}}" tabindex="{{bbSplitpanelItemIsActive ? 0 : -1}
This shouldn't be bb-custom-content-selectable-item, it should be prefixed with something splitpanel specific.

2017-07-12 20:41 UTC, Blackbaud-PatrickOFriel commented on js/sky/templates/splitpanel/splitpanel.list.panel.directive.html
> +<div class="bb-custom-content" id="splitpanel_list" style="max-width:{{maxWidthInPercentage}}%; min-width:{{minWidthInPercentage  }}%">
You should also probably use ng-style instead of inline-ing styles with angular bindings in the template

2017-07-12 20:43 UTC, Blackbaud-PatrickOFriel commented on js/sky/templates/splitpanel/splitpanel.container.component.html
> +<div class="split-pattern-container" id="container">
Do not use ids unless you absolutely have to. Because they need to be unique. Also should the class be split-panel-container?

2017-07-12 20:43 UTC, Blackbaud-PatrickOFriel commented on js/sky/templates/splitpanel/splitpanel.list.item.component.html
> +<div class="bb-custom-content-selectable-item" ng-click="selectItem()" ng-class="{'selectedItem': bbSplitpanelItemIsActive}" id="item{{$parent.$index}}" tabindex="{{bbSplitpanelItemIsActive ? 0 : -1}
Do not use ids unless you absolutely have to, because you need to ensure they are unique.

2017-07-12 20:44 UTC, Blackbaud-PatrickOFriel commented on js/sky/templates/splitpanel/splitpanel.list.panel.directive.html
> +<div class="bb-custom-content" id="splitpanel_list" style="max-width:{{maxWidthInPercentage}}%; min-width:{{minWidthInPercentage  }}%">
Do not use ids unless you absolutely have to, because you have to ensure that they are unique

2017-07-12 20:45 UTC, Blackbaud-PatrickOFriel commented on js/sky/templates/splitpanel/splitpanel.workspace.component.html
> +<bb-modal class="split-panel-workspace bb-splitpanel-hidden" id="workspace">
This shouldn't be bb-custom-content, it should be prefixed with something splitpanel specific.

2017-07-12 20:49 UTC, Blackbaud-PatrickOFriel commented on js/sky/src/splitpanel/splitpanel.list.item.directive.js
> +                        var elem = angular.element('.bb-custom-content');
What exactly are you trying to do with the all the addClass('bb-splitpanel-hidden') here?

2017-07-12 20:51 UTC, Blackbaud-PatrickOFriel commented on js/sky/src/splitpanel/splitpanel.list.item.directive.js
> +                        $scope.$parent.item.$index = $scope.$parent.$index;
We should not assume what $parent is here. Instead use the `require` attribute for this directive to access parent directive/component information.

2017-07-12 20:57 UTC, Blackbaud-PatrickOFriel commented on js/sky/src/splitpanel/splitpanel.list.panel.directive.js
> +                    $($window).resize(function () {
This event handler needs to have a corresponding `off` on directive destroy. To do this you need to name the window resize handler specific to this implementation: i.e. `$($window).on('resize.splitPanelListPanel' + $scope.$id, function () {})` and `$($window).off('resize.splitPanelListPanel' + $scope.$id)` on directive destroy

2017-07-12 20:59 UTC, Blackbaud-PatrickOFriel commented on js/sky/src/splitpanel/splitpanel.list.panel.directive.js
> +                    $("#splitpanel_list").resizable();
Dont use ids, you can access el from the directive link function, and then use `el.find('.directive-child-class')` to keep the element search scoped to this specific component, not searching the entire page for an id.

2017-07-12 21:01 UTC, Blackbaud-PatrickOFriel commented on js/sky/src/splitpanel/splitpanel.mobile.list.back.component.js
> +                        var elem = angular.element('.bb-custom-content');
Same question as above

2017-07-12 21:03 UTC, Blackbaud-PatrickOFriel commented on js/sky/src/splitpanel/splitpanel.factory.js
> +    angular.module('sky.splitpanel.bbCheckDirtyForm.factory', ['sky.modal'])
This doesn't need to be under `splitpanel` it's a generic check dirty form function. Also, don't use camel case in these modules

2017-07-12 21:07 UTC, Blackbaud-PatrickOFriel commented on js/sky/src/splitpanel/splitpanel.workspace.component.js
> +            replace: true,
Don't use replace: true if you can avoid it (I don't even think its allowed for components so this probably isnt doing anything https://docs.angularjs.org/guide/component)

2017-07-12 21:07 UTC, Blackbaud-PatrickOFriel commented on js/sky/src/splitpanel/splitpanel.list.item.directive.js
> +                replace: true,
Avoid using replace: true

2017-07-12 21:10 UTC, Blackbaud-PatrickOFriel commented on js/sky/templates/splitpanel/splitpanel.content.custom.component.html
> +<div class="bb-listbuilder-content-custom" ng-if="$ctrl.viewIsActive()">
Is this file being used? If so why does it have the 'custom' stuff in it instead of being scoped to split panel?

2017-07-12 21:10 UTC, Blackbaud-PatrickOFriel commented on js/sky/templates/splitpanel/splitpanel.footer.component.html
> +<div class="bb-listbuilder-footer">
Is this being used anywhere?

2017-07-12 21:11 UTC, Blackbaud-PatrickOFriel commented on js/sky/templates/splitpanel/splitpanel.list.component.html
> +<div class="split-panel-list-container">
prefix this and all your classes with bb

2017-07-12 21:12 UTC, Blackbaud-PatrickOFriel commented on js/sky/templates/splitpanel/splitpanel.list.fixed.header.filter.component.html
> +<div class="hidden-xs fixedHeader" style="padding-top: 6px;">
Don't use inline styles. for classes you create use hyphens instead of camel case and prefix with bb

2017-07-12 21:12 UTC, Blackbaud-PatrickOFriel commented on js/sky/templates/splitpanel/splitpanel.list.fixed.header.item.component.html
> +<div class="fixedHeader">
for classes you create use hyphens instead of camel case and prefix with bb

2017-07-12 21:14 UTC, Blackbaud-PatrickOFriel commented on js/sky/templates/splitpanel/splitpanel.mobile.list.next.component.html
> +<span type="button" class="glyphicon glyphicon-menu-down bb-splitpanel-next-navigation" ng-click="$ctrl.bbSplitpanelListNextClick()"></span>
A span can't be of type button. Use an actual button or a role of button with a tabindex of 0. use font-awesome instead of glyphicon

2017-07-12 21:14 UTC, Blackbaud-PatrickOFriel commented on js/sky/templates/splitpanel/splitpanel.mobile.list.previous.component.html
> +<span type="button" class="glyphicon glyphicon-menu-up bb-splitpanel-previous-navigation" ng-click="$ctrl.bbSplitpanelListPreviousClick()"></span>
A span can't be of type button. Use an actual button or a role of button with a tabindex of 0. use font-awesome instead of glyphicon

2017-07-12 21:14 UTC, Blackbaud-PatrickOFriel commented on js/sky/templates/splitpanel/splitpanel.mobile.selected.item.component.html
> +<div class="bb-custom-content-item-xs selected-item-xs bb-splitpanel-show-xs">
Don't use the custom prefix, ensure that selected-item is prefixed with bb

2017-07-12 21:16 UTC, Blackbaud-PatrickOFriel commented on js/sky/templates/splitpanel/splitpanel.mobile.workspace.header.component.html
> +<div class="modal-header bb-splitpanel-show-xs">
Isn't this supposed to be `bb-modal-header`? And why are you using modal styles here while not in a modal?

2017-07-12 21:17 UTC, Blackbaud-PatrickOFriel commented on js/sky/templates/splitpanel/splitpanel.workspace.container.component.html
> +    <div class="split-panel-workspace-container">
Use bb prefixes

2017-07-12 21:19 UTC, Blackbaud-PatrickOFriel commented on scss/_splitpanel.scss
> +        border-bottom: 1px solid grey;
Use one of our scss variables instead of the browser gray. You can ask @Blackbaud-ToddRoberts or your designer what the actual hex code should be

2017-07-12 21:20 UTC, Blackbaud-PatrickOFriel commented on scss/_splitpanel.scss
> +    .split-pattern-container {
All these need to have the bb prefixes that I mentioned above

2017-07-12 21:20 UTC, Blackbaud-PatrickOFriel commented on scss/_splitpanel.scss
> +        border-right: 1px solid #f3f3f4;
Use our border color variables or mixins

2017-07-12 21:20 UTC, Blackbaud-PatrickOFriel commented on scss/_splitpanel.scss
> +        border-left: 9px solid #f3f3f4;
Same as above

2017-07-12 21:21 UTC, Blackbaud-PatrickOFriel commented on scss/_splitpanel.scss
> +    .selectedItem {
Use hyphens instead of camel case

2017-08-18 07:23 UTC, Rahulitsmca commented on js/sky/src/splitpanel/docs/demo.html
> +                            <div class="bb-custom-content-item" bb-splitpanel-list-item ng-repeat="item in listCtrl.data" bb-listbuilder-content-get-panel-data="listCtrl.splitpanelNavigator.checkDirt
updated this to bb-splitpanel-content-get-panel-data.

2017-08-18 07:23 UTC, Rahulitsmca commented on js/sky/src/splitpanel/docs/demo.md
> +`bbCheckDirtyForm.invokeMethodWithParameters` &mdash; Invoke the passed method with parameter.
yes sure, removed it.

2017-08-18 07:25 UTC, Rahulitsmca commented on js/sky/src/splitpanel/docs/demo.js
> +                occupation: 'Amazon market palce amz.com',
made occupation to description.

2017-08-18 07:31 UTC, Rahulitsmca commented on js/sky/src/splitpanel/docs/demo.js
> +                joinDate: new Date('09/14/2016'),
made it transactionDate. looks more appropriate.

2017-08-18 07:32 UTC, Rahulitsmca commented on js/sky/src/splitpanel/docs/demo.js
> +                occupation: 'Wallmart',
corrected.

2017-08-18 07:32 UTC, Rahulitsmca commented on js/sky/src/splitpanel/docs/demo.js
> +            //TODO: loadData with filter of unrecorded transcation
removed these comments

2017-08-18 07:36 UTC, Rahulitsmca commented on js/sky/src/splitpanel/docs/demo.md
> +			- `bb-splitpanel-list ` &mdash; Placeholder for list.
added them in documentation.

2017-08-18 07:37 UTC, Rahulitsmca commented on js/sky/src/splitpanel/splitpanel.list.filter.component.js
> +///* global angular */
removed these comments.

2017-08-18 07:38 UTC, Rahulitsmca commented on js/sky/src/splitpanel/splitpanel.list.item.directive.js
> +                    bbListbuilderContentGetPanelData: '&?'
updated it to bbSplitpanelContentGetPanelData

2017-08-18 07:40 UTC, Rahulitsmca commented on js/sky/templates/splitpanel/splitpanel.list.panel.directive.html
> +<div class="bb-custom-content" id="splitpanel_list" style="max-width:{{maxWidthInPercentage}}%; min-width:{{minWidthInPercentage  }}%">
prefixed this class with bb-splitpanel.
used ng-style in place of style
used class in place of id.

2017-08-18 07:41 UTC, Rahulitsmca commented on js/sky/templates/splitpanel/splitpanel.list.item.component.html
> +<div class="bb-custom-content-selectable-item" ng-click="selectItem()" ng-class="{'selectedItem': bbSplitpanelItemIsActive}" id="item{{$parent.$index}}" tabindex="{{bbSplitpanelItemIsActive ? 0 : -1}
prefixed this class with bb-splitpanel and used class in place of id.

2017-08-18 07:43 UTC, Rahulitsmca commented on js/sky/templates/splitpanel/splitpanel.container.component.html
> +<div class="split-pattern-container" id="container">
removed id and updated class name to bb-splitpanel-container

2017-08-18 07:45 UTC, Rahulitsmca commented on js/sky/templates/splitpanel/splitpanel.workspace.component.html
> +<bb-modal class="split-panel-workspace bb-splitpanel-hidden" id="workspace">
made it bb-splitpanel-workspace.

2017-08-18 13:50 UTC, Rahulitsmca commented on scss/_splitpanel.scss
> +        border-bottom: 1px solid grey;
used $gray variable from _variables.scss.

2017-08-18 13:50 UTC, Rahulitsmca commented on js/sky/templates/splitpanel/splitpanel.workspace.container.component.html
> +    <div class="split-panel-workspace-container">
done.

2017-08-18 13:51 UTC, Rahulitsmca commented on js/sky/templates/splitpanel/splitpanel.mobile.workspace.header.component.html
> +<div class="modal-header bb-splitpanel-show-xs">
done, removed modal's css.

2017-08-18 13:51 UTC, Rahulitsmca commented on js/sky/templates/splitpanel/splitpanel.mobile.selected.item.component.html
> +<div class="bb-custom-content-item-xs selected-item-xs bb-splitpanel-show-xs">
done

2017-08-18 13:53 UTC, Rahulitsmca commented on js/sky/templates/splitpanel/splitpanel.mobile.list.previous.component.html
> +<span type="button" class="glyphicon glyphicon-menu-up bb-splitpanel-previous-navigation" ng-click="$ctrl.bbSplitpanelListPreviousClick()"></span>
Used font awesome in place of glyphicon.

2017-08-18 13:53 UTC, Rahulitsmca commented on js/sky/templates/splitpanel/splitpanel.mobile.list.next.component.html
> +<span type="button" class="glyphicon glyphicon-menu-down bb-splitpanel-next-navigation" ng-click="$ctrl.bbSplitpanelListNextClick()"></span>
Used font awesome in place of glyphicon.

2017-08-18 13:54 UTC, Rahulitsmca commented on js/sky/templates/splitpanel/splitpanel.list.fixed.header.item.component.html
> +<div class="fixedHeader">
updated it bb-splitpanel-fixed-header.

2017-08-18 13:57 UTC, Rahulitsmca commented on js/sky/templates/splitpanel/splitpanel.list.fixed.header.filter.component.html
> +<div class="hidden-xs fixedHeader" style="padding-top: 6px;">
Removed inline style and used class for it.

2017-08-18 13:57 UTC, Rahulitsmca commented on js/sky/templates/splitpanel/splitpanel.list.component.html
> +<div class="split-panel-list-container">
done.

2017-08-18 13:57 UTC, Rahulitsmca commented on js/sky/templates/splitpanel/splitpanel.footer.component.html
> +<div class="bb-listbuilder-footer">
No. Removed unused file.

2017-08-18 13:57 UTC, Rahulitsmca commented on js/sky/src/splitpanel/splitpanel.list.item.directive.js
> +                replace: true,
removed.

2017-08-18 14:00 UTC, Rahulitsmca commented on js/sky/src/splitpanel/splitpanel.factory.js
> +    angular.module('sky.splitpanel.bbCheckDirtyForm.factory', ['sky.modal'])
Created independent module for checkDirtyForm and consumed it in spit panel.

2017-08-18 14:03 UTC, Rahulitsmca commented on scss/_splitpanel.scss
> +    .selectedItem {
updated it ot bb-splitpanel-selected-item.

2017-08-18 14:11 UTC, Rahulitsmca commented on scss/_splitpanel.scss
> +    .split-pattern-container {
done.

2017-08-18 14:15 UTC, Rahulitsmca commented on scss/_splitpanel.scss
> +        border-left: 9px solid #f3f3f4;
removed hard coded f3f3f4 and used $body-bg.

2017-08-18 14:40 UTC, Rahulitsmca commented on js/sky/src/splitpanel/splitpanel.list.panel.directive.js
> +                    $("#splitpanel_list").resizable();
Removed id.

2017-08-18 14:40 UTC, Rahulitsmca commented on js/sky/src/splitpanel/splitpanel.workspace.component.js
> +            replace: true,
removed it.

2017-08-18 14:41 UTC, Rahulitsmca commented on js/sky/src/splitpanel/splitpanel.list.item.directive.js
> +                        var elem = angular.element('.bb-custom-content');
hiding list on item click only for mobile view.

2017-08-18 14:51 UTC, Rahulitsmca commented on js/sky/src/splitpanel/docs/demo.js
> +            var code = event.keyCode;
We are not separating out this feature in this version. Let's have this in demo page. 
If everyone need this feature we'll extend this with enable/disable functionality.

2017-08-22 19:33 UTC, Blackbaud-BobbyEarl commented
@blackbaud-sky-savage retry

2017-08-22 19:39 UTC, blackbaud-sky-savage commented
**Tests failed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: b9edcdb0b5990eaf43d5731bda196b1769755e5e
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/267318876

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

2017-09-18 08:05 UTC, blackbaud-sky-savage commented
**Tests failed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 9b8160ee2b7a4b1869afadb399d35d292d02acb7
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/276744574

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

2017-09-26 11:19 UTC, blackbaud-sky-savage commented
**Tests failed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 16e1d872ff4b9ad635c44de5d6b03b406024ac2e
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/279914929

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

2017-09-26 12:18 UTC, blackbaud-sky-savage commented
**Tests failed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 53653d85730eec62e28b37fc17d09df649ec0063
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/279926236

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

2017-09-26 13:04 UTC, blackbaud-sky-savage commented
**Tests passed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: 9d36c59ae853fc701388172f09fc4ff264c33afd
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/279945180

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

2017-11-14 15:46 UTC, blackbaud-danbowman commented
Thanks @Rahulitsmca for your efforts on this pull request. Our team has discussed with yours and determined best course is to **not** proceed with bringing the Split View component into the SKY UX library. Instead, we'll set our sights on making it an available component in the SKY UX 2 library, and in the meantime your team is set with the split view functionality already implemented.

Regards,
SKY UX team

2017-11-14 15:46 UTC, closed without merging