Tabbed sectioned form implementation
blackbaud/skyux1 pull request #988
Opened 2017-02-07 17:43 UTC by Blackbaud-DanielCooke

2017-02-07 17:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/blackbaud/skyux?pullRequest=988) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/blackbaud/skyux?pullRequest=988) before we can accept your contribution.<br/>

2017-02-07 17:59 UTC, blackbaud-sky-savage commented
**Tests passed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: 38e6dace21197d4dc1cd347b68e2d04038bffe56
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/199309246

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

2017-02-07 20:08 UTC, Blackbaud-PatrickOFriel commented
Hey @Blackbaud-DanielCooke , I'll take a look at this more in-depth later this week, but the first thing I noticed was that you were using an element directive instead of a component. As of AngularJS 1.5.x, we've been trying to write all of our new features using the component API since that's what the Angular team has been recommending (it also matches more closely to how Angular 2 works which gives us more consistency there as well). See https://docs.angularjs.org/guide/component for an example. You can also see a simple SKY UX component example in our alert source code https://github.com/blackbaud/skyux/blob/master/js/sky/src/alert/alert.component.js.

Let me know if you have any questions!

2017-02-08 19:27 UTC, blackbaud-sky-savage commented
**Tests passed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: 882b0bd1d738d6b4814d9937c35d4010562edf7a
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/199722273

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

2017-02-09 13:45 UTC, Blackbaud-DanielCooke commented
Thanks, @Blackbaud-PatrickOFriel.  I've done most of the conversion over to use a component.  There are still a couple of things I want to try out so I don't have to inject $scope into the component

- Get rid of the $scope.$watch on the activeSection
Possibly use the select() callback property on each tab instead
- Get rid of the $scope.$on('reinitializeSectionDisplay')...
Unsure as to the best way to accomplish this as the moment
- Get rid of the $scope.$emit('sectionsVisibilityChanged')
Change to use bound callback function

2017-02-09 14:34 UTC, Blackbaud-PatrickOFriel commented
Yeah I agree with using a callback instead of the `sectionsVisibilityChanged`. 

For the `reinitializeSectionDisplay` event, I'm not sure that there's a much better way to that in AngularJS so that might be the way to go. 

For the $watch on `activeSection`, because you're working around the external tab directive, I wouldn't worry too much about having to use $watch if using the select() callback doesn't work easily, just because you're working around something we don't control all the bits of.

2017-02-09 18:52 UTC, blackbaud-sky-savage commented
**Tests failed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 4eebc9355de51c3627e01f0822eee838dbee351e
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/200086736

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

2017-02-09 19:17 UTC, Blackbaud-PatrickOFriel commented
@blackbaud-sky-savage retry

2017-02-09 19:26 UTC, blackbaud-sky-savage commented
**Tests failed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 4eebc9355de51c3627e01f0822eee838dbee351e
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/200098166

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

2017-02-09 19:27 UTC, Blackbaud-PatrickOFriel commented
@blackbaud-sky-savage retry

2017-02-09 19:41 UTC, blackbaud-sky-savage commented
**Tests failed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 4eebc9355de51c3627e01f0822eee838dbee351e
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/200100667

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

2017-02-09 19:43 UTC, Blackbaud-PatrickOFriel commented
Hey @Blackbaud-DanielCooke a bunch of visual tests look to be failing because browserstack changed graphics cards on their machines or something. I'll correct the tests and then update your branch

2017-02-09 21:52 UTC, blackbaud-sky-savage commented
**Tests passed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: 75aa3b7221687d6f22828c1809240889206f064e
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/200143332

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

2017-02-10 14:50 UTC, Blackbaud-PatrickOFriel requested changes
Looks good, just have a couple minor changes that I requested in the inline comments

2017-02-10 14:50 UTC, Blackbaud-PatrickOFriel commented on js/sky/src/sectionedform/sectionedmodal.directive.js
> +        .directive('bbSectionedModal', function () {
Let's add a reference to this attribute directive in the documentation for sectioned form

2017-02-10 14:50 UTC, Blackbaud-PatrickOFriel commented on scss/_sectionedform.scss
> +            border-right-style: none !important;
any chance we can get rid of the `!important` here by using more specific selectors? We try to only use `!important` if we need to override inline styles or something.

2017-02-10 14:50 UTC, Blackbaud-PatrickOFriel commented on scss/_sectionedform.scss
> +                background-color: $gray-lightest !important;
Same as above in terms of !important

2017-02-10 14:50 UTC, Blackbaud-PatrickOFriel commented on js/sky/src/sectionedform/sectionedform.component.js
> +            if (vm.isMobile !== breakpoints.xs) {
Looks like the else case here wasn't covered, so we either need to explicitly ignore it, or add a test to cover it. You can check the code coverage by looking in the coverage folder.

2017-02-10 14:50 UTC, Blackbaud-PatrickOFriel commented on js/sky/src/sectionedform/sectionedform.component.js
> +            if (angular.isFunction(vm.onSectionsVisibilityChange)) {
The else of this branch also isn't covered

2017-02-10 15:00 UTC, Blackbaud-PatrickOFriel commented on js/sky/src/sectionedform/sectionedform.component.js
> +                form: '^^form'
One last question, is there any reason that the parent form element controller is required? Do we reference it anywhere?

2017-02-13 12:40 UTC, Blackbaud-DanielCooke commented on js/sky/src/sectionedform/sectionedform.component.js
> +            if (vm.isMobile !== breakpoints.xs) {
I think it is probably better to ignore these instead of write a test that expects it to do nothing.

2017-02-13 12:46 UTC, Blackbaud-DanielCooke commented on js/sky/src/sectionedform/sectionedform.component.js
> +                form: '^^form'
I use it to get the child form controllers so I can tell if a section is invalid or has required fields.  I could make it optional if you prefer

2017-02-13 14:10 UTC, Blackbaud-PatrickOFriel commented on js/sky/src/sectionedform/sectionedform.component.js
> +            if (vm.isMobile !== breakpoints.xs) {
Okay, then above the if statement add a comment like:

```
/* istanbul ignore else */
/* sanity check */
```

2017-02-13 14:13 UTC, Blackbaud-PatrickOFriel commented on js/sky/src/sectionedform/sectionedform.component.js
> +                form: '^^form'
Ah I see now, nope let's keep it required, in the future, if someone specifically needs it to not be required we can update it.

2017-02-13 16:26 UTC, blackbaud-sky-savage commented
**Tests passed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: a0bc85698d296302ad1c6cce01c756549e57ef8e
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/201178282

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

2017-02-13 19:31 UTC, blackbaud-sky-savage commented
**Tests failed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: c2471fff1656e5139d5e5e74a583663ad9b5f3ab
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/201240024

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

2017-02-13 19:45 UTC, blackbaud-sky-savage commented
**Tests passed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: 1a8887dbf913629124b29d5df3912646a12e169a
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/201242155

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

2017-02-13 21:03 UTC, Blackbaud-PatrickOFriel approved these changes

2017-02-13 21:03 UTC, merged